# Generated by Django 3.0.7 on 2020-06-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('url_hash', models.CharField(db_index=True, max_length=10, unique=True)),
                ('short_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
